name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy
    runs-on: am
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /group_project_team_35
            git pull origin main  
          EOF

